name: Build ROCm Windows Wheel

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build ROCm wheel
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: 'v0.1.77'
      - uses: actions/checkout@v3
        with:
          repository: 'SlyEcho/llama.cpp'
          path: 'vendor/llama.cpp'
          ref: 'hipblas'
          
      - name: Install ROCm SDK
        run: |
          curl -LO https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe
          Start-Process 'AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe' -ArgumentList '-install' -NoNewWindow -Wait
          echo "C:\Program Files\AMD\ROCm\5.5\bin" >> $env:GITHUB_PATH
          echo 'ROCM_PATH=C:\Program Files\AMD\ROCm\5.5' >> $env:GITHUB_ENV
          echo 'HIP_PATH=C:\Program Files\AMD\ROCm\5.5' >> $env:GITHUB_ENV
          echo "ROCM_VERSION=5.5.1" >> $env:GITHUB_ENV
          
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}
          
      - name: Install Dependencies
        run: |
          python -m pip install build wheel cmake scikit-build ninja
        
      - name: Build Wheel
        run: |
          $env:CC = 'C:\Program Files\AMD\ROCm\5.5\bin\clang.exe'
          $env:CXX = 'C:\Program Files\AMD\ROCm\5.5\bin\clang++.exe'
          $env:CMAKE_PREFIX_PATH = 'C:\Program Files\AMD\ROCm\5.5'
          $env:VERBOSE = '1'
          pushd '.\vendor\llama.cpp'
          cmake -B build -G "Ninja" -DLLAMA_HIPBLAS=ON "-DCMAKE_HIP_ARCHITECTURES=gfx1030;gfx1100" -DBUILD_SHARED_LIBS=ON
          cmake --build build --config Release --target llama
          Copy-Item '.\build\bin\Release\llama.dll' '..\..\llama_cpp'
          popd
          python setup.py --skip-cmake bdist_wheel egg_info --tag-build=+rocm5.5.1
        
      - uses: actions/upload-artifact@v3
        with:
          name: 'wheels'
          path: ./dist/*.whl
