name: Build All Wheels

on: workflow_dispatch

permissions:
  contents: write
  
jobs:
  run_workflow_0-1-62:
    name: Build Wheels 0.1.62
    uses: ./.github/workflows/build-wheels-0.1.62.yml
    
  run_workflow_0-1-66:
    name: Build Wheels 0.1.66
    needs: run_workflow_0-1-62
    uses: ./.github/workflows/build-wheels-0.1.66.yml
    
  run_workflow_0-1-67:
    name: Build Wheels 0.1.67
    needs: run_workflow_0-1-66
    uses: ./.github/workflows/build-wheels-0.1.67.yml
    
  run_workflow_0-1-68:
    name: Build Wheels 0.1.68
    needs: run_workflow_0-1-67
    uses: ./.github/workflows/build-wheels-0.1.68.yml
    
  run_workflow_0-1-70:
    name: Build Wheels 0.1.70
    needs: run_workflow_0-1-68
    uses: ./.github/workflows/build-wheels-0.1.70.yml
    
  run_workflow_0-1-71:
    name: Build Wheels 0.1.71
    needs: run_workflow_0-1-70
    uses: ./.github/workflows/build-wheels-0.1.71.yml
    
  run_workflow_0-1-72:
    name: Build Wheels 0.1.72
    needs: run_workflow_0-1-71
    uses: ./.github/workflows/build-wheels-0.1.72.yml
