name: Build Wheels test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.85'
        default: 'v0.1.85'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.85'
        default: 'v0.1.85'
        required: false
        type: string

jobs:
  build_wheels_main:
    name: ${{ matrix.os }} ${{ matrix.pyver }} ${{ matrix.avx }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-12, macos-11]
        arch: ["x86_64","arm64"]
        pyver: ["3.10"]
    env:
      CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}
      PCKGVER: ${{ inputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: ${{ inputs.version }}
          submodules: 'recursive'
          
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
          
      - name: Install Dependencies
        run: |
          python -m pip install build wheel cmake
          
      - name: Build Wheel
        run: |
          export CMAKE_ARGS="-DLLAMA_METAL=on"
          VERBOSE=1 python -m build --wheel
        
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ format('wheel-{0}-{1}', matrix.os, matrix.arch)  }}
          path: ./dist/*.whl
