name: Build Wheels for New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.78'
        default: 'v0.1.78'
        required: true
        type: string

permissions:
  contents: write
  
jobs:
  run_main:
    name: Build ${{ inputs.version }} CUDA Wheels
    uses: ./.github/workflows/build-wheels.yml
    with:
      version: ${{ inputs.version }}
      
  run_ooba:
    name: Build ${{ inputs.version }} CUDA Wheels for Text Generation Webui
    needs: run_main
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      
  run_rocm:
    name: Build ROCm 5.5.1 Windows Wheels ${{ inputs.version }}
    needs: run_ooba
    uses: ./.github/workflows/build-wheel-rocm-windows.yml
    with:
      version: ${{ inputs.version }}
